package.json
src/SectionWrapper/index.tsx
src/SectionWrapper/stories.tsx
src/index.ts

feat(SectionWrapper): create component + story

---

package.json
src/Search/index.tsx
src/Search/stories.tsx

feat(Search): create component + story

---

package.json
src/StatsCard/index.tsx
src/StatsCard/stories.tsx
src/index.ts

feat(StatsCard): create component + story

---

package.json
src/EmptyState/index.tsx
src/EmptyState/stories.tsx

feat(EmptyState): add children + dark variant

---

package.json
src/Breadcrumbs/index.tsx
src/Breadcrumbs/stories.tsx
src/index.ts

feat(Breadcrumbs): add component + story

---

package.json
src/Forms/JsonTextArea/index.tsx
src/Forms/JsonTextArea/stories.tsx
src/index.ts

feat(JsonTextArea): create component + stories

---

package.json
src/Table/index.tsx
src/Table/stories.tsx
src/index.ts

feat(Table): create component + stories

---

package.json
src/Sections/SourceDestination/index.tsx

feat(SourceDestination): make ellipse mandatory

---

.storybook/preview-head.html
package.json
src/Sections/Amount/index.tsx
src/Typography/stories.tsx
src/muiTheme.ts

improvement(Typo): add bold and money variant + use Roboto mono

---

package.json
src/Sections/SourceDestination/index.tsx
src/Sections/SourceDestination/stories.tsx
src/Sections/Txid/index.tsx

improvement(): add color for SourceDest, use money variant for Txid

---

src/OnBoarding/index.tsx
src/OnBoarding/stories.tsx
src/index.ts

feat(OnBoarding): Add Onboarding component to the storybook with stories

---

package.json
src/Search/index.tsx

feat(Search): handle key interaction

---

package.json
src/Table/Filters/AutocompleteSelect/stories.tsx
src/Table/index.tsx
src/Table/stories.tsx

feat(Table): add active filters

---

package.json
src/Forms/FormHelper/index.tsx
src/Forms/RadioGroup/index.tsx
src/Forms/RadioGroup/stories.tsx
src/Forms/TextArea/index.tsx
src/index.ts
src/types.ts

feat(RadioGroup): add component + story (MERGE 1)

---

.husky/pre-push
package.json
src/Forms/DatePicker/index.tsx
src/Forms/DatePicker/stories.tsx
src/Forms/DebouncedAutocomplete/index.tsx
src/Forms/DebouncedAutocomplete/stories.tsx
src/Forms/FormHelper/index.tsx
src/Forms/RadioGroup/index.tsx
src/Forms/Select/index.tsx
src/Forms/Select/stories.tsx
src/Forms/TextField/index.tsx
src/Forms/TextField/stories.tsx
src/Modal/stories.tsx
src/index.ts
src/types.ts
src/utils.ts

feat(): Select and DebouncedAutocomplete + stories + put build hook on pre-push + refactor (MERGE 2)

---

package.json
src/Buttons/Tabs/index.tsx
src/Buttons/Tabs/stories.tsx

feat(Tabs): add action button

---

package.json
src/Buttons/Tabs/index.tsx
src/Buttons/Tabs/stories.tsx
src/Modal/stories.tsx

feat(Tabs): add action children instead of button

---

package.json
src/Forms/TextField/index.tsx

fix(TextField): remove inputRef from props for label to remove warning

---

package.json
src/Navbar/index.tsx

fix(Navbar): use includes instead of first item

---

package.json
src/Modal/index.tsx

style(): remove hover background

---

package.json
src/Forms/Pickers/DatePicker/index.tsx
src/Forms/Pickers/DatePicker/stories.tsx
src/Forms/Pickers/DateTimePicker/index.tsx
src/Forms/Pickers/DateTimePicker/stories.tsx
src/index.ts

feat(DateTimePicker): add component + story + refactor file tree

---

package.json
src/Chip/index.tsx
src/Chip/stories.tsx
src/Forms/TextArea/index.tsx

fix(): text area + chip

---

package.json
src/Sections/Secret/index.tsx
src/Sections/Secret/stories.tsx
src/index.ts

feat(Secret): component + stories

---

package.json
src/Breadcrumbs/stories.tsx
src/Buttons/LoadingButton/index.tsx
src/Chip/index.tsx
src/Containers/EmptyState/stories.tsx
src/Containers/Page/stories.tsx
src/Dataviz/StatsCard/index.tsx
src/Dataviz/StatsCard/stories.tsx
src/Forms/DebouncedAutocomplete/index.tsx
src/Forms/Switch/index.tsx
src/Forms/Switch/stories.tsx
src/Navbar/index.tsx
src/Typography/stories.tsx
src/index.ts
src/muiTheme.ts
src/types.ts
src/utils.ts
yarn.lock

feat(Switch): component + stories + refactor / fix

---

package.json
src/Forms/Select/stories.tsx
src/Forms/SelectMultiple/index.tsx
src/Forms/SelectMultiple/stories.tsx
src/index.ts

feat(SelectMultiple): component + stories

---

package.json
src/index.ts

fix(): missing export

---

package.json
src/index.ts

fix(ShellViewer): export

---

package.json
src/Modal/index.tsx
src/Viewers/Shell/index.tsx
src/Viewers/Shell/stories.tsx

style(): adjust padding on modal

---

package.json
src/OnBoarding/index.tsx
src/Search/index.tsx

style(): adjust UI

---

package.json
src/Table/index.tsx
src/Table/stories.tsx

feat(Table): add column sorting

---

.storybook/preview.js
package.json
src/Search/index.tsx
src/Search/stories.tsx
src/Table/index.tsx

style(): search + pagination table

---

package.json
src/Containers/Page/index.tsx

style(Page): change padding

---

package.json
src/Breadcrumbs/index.tsx

style(Breadcrumbs): remove font weight from link

---

package.json
src/Dataviz/StatsCard/index.tsx
src/Dataviz/StatsCard/stories.tsx

style(StatCard): add light version

---

package.json
src/Dataviz/StatsCard/index.tsx
src/Dataviz/StatsCard/stories.tsx

style(StatCard): add sx props

---

package.json
src/Sections/CopyPasteTooltip/index.tsx
src/Sections/CopyPasteTooltip/stories.tsx
src/Sections/Secret/index.tsx

feat(CopyPaste): create compoent + story + refactor Secret Component

---

package.json
src/index.ts

fix(CopyPaste): export

---

package.json
src/Table/index.tsx

fix(Table): remove pagination total when total.value is undefined

---

package.json
src/Table/index.tsx

fix(Table): use appropriate value for hasMore and pageSize

---

package.json
src/Containers/Page/index.tsx

fix: page title width
